import type { NextPage } from "next";
import Head from "next/head";
import BodySingle from "integrador/components/layouts/body/single/body-single.component";
import Container from "@mui/material/Container";
import LogIn from "integrador/components/forms/logIn/log-in-form.component";
import { LoginProvider } from "integrador/components/contexts/LoginContext";
import { StepProvider } from "integrador/components/contexts/StepContext";
import { useMediaQuery } from "@mui/material";
import { theme } from "integrador/styles/material-theme";
import { useEffect } from "react";
import { useRouter } from "next/router";
import ErrorBalance from "integrador/components/ErrorBalance";
import PageHomeLayout from "integrador/components/layouts/layout-home.component";
import SignInLayout from "integrador/components/layouts/layout-sign-in.component";

export const InsuficcientBalancePage: NextPage = () => {
  const laptopOrDesktop = useMediaQuery(theme.breakpoints.up("laptop"));

  const router = useRouter();

//   useEffect(() => {
//     const tokenId = localStorage.getItem("token");
//     if (tokenId) {
//       router.push("/home");
//     }
//   }, []);

  return (
    <>
      <Head>
        <title>Iniciar sesion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Container
          sx={{
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "center",
            alignItems: "flex-end",
            height: "100%",
            alignContent: "start",
          }}
          maxWidth={false}
        >
          <ErrorBalance />
        </Container>
    </>
  );
};

(InsuficcientBalancePage as any).Layout = PageHomeLayout;

export default InsuficcientBalancePage;
